dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

install: 
   - pip3 install --upgrade pip 
   - pip install coveralls
   - pip install pytest
   - pip install stripe
   - pip install selenium
   - npm install lcov-parse
   - wget -N http://chromedriver.storage.googleapis.com/72.0.3626.7/chromedriver_linux64.zip -P ~/
   - unzip ~/chromedriver_linux64.zip -d ~/
   - rm ~/chromedriver_linux64.zip
   - sudo mv -f ~/chromedriver /usr/local/share/
   - sudo chmod +x /usr/local/share/chromedriver
   - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

addons: # get google-chrome-stable
  chrome: stable

before_install:
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=8000 http://127.0.0.1 &

script:
  - pytest test.py -v

after_success:
 - coveralls
notifications:
  webhooks:
    - http://str-expert-cert-3359.botics.co/api/v1/challenge/check_builds/
